computer_data = [{"category": "Science: Computers",
                  "type": "boolean", "difficulty": "medium",
                  "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                  "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "The open source program Redis is a relational database server.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "AMD created the first consumer 64-bit processor.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "It&#039;s not possible to format a write-protected DVD-R Hard Disk.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Linux was first created as an alternative to Windows XP.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                  "question": "Android versions are named in alphabetical order.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
